# Generated by Django 5.0.6 on 2026-08-16 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rhymes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('icon_emoji', models.CharField(default='🏅', max_length=8)),
                ('criteria_type', models.CharField(choices=[('rhymes_completed', 'Number of rhymes completed'), ('quiz_score_perfect', 'Number of perfect quiz scores'), ('repeat_master', 'Total repeat plays across all rhymes'), ('quizzes_taken', 'Number of quizzes completed')], max_length=30)),
                ('criteria_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RhymeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_played', models.PositiveIntegerField(default=0)),
                ('repeat_count', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='rhymes.rhyme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhyme_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rhyme')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='progress.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
