# Generated by Django 5.0.6 on 2026-08-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_constraints_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at']},
        ),
        migrations.RenameIndex(
            model_name='rhymeprogress',
            new_name='progress_rh_user_id_d1c384_idx',
            old_name='progress_rhyme_user_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='rhymeprogress',
            new_name='progress_rh_user_id_5d848e_idx',
            old_name='progress_rhyme_user_last_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rhymeprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set(),
        ),
    ]
