# Generated by Django 5.0.6 on 2026-08-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon_emoji', models.CharField(default='🎵', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short, simple description for parents.')),
                ('lyrics', models.TextField(help_text='Full lyrics text, shown alongside the video/audio.')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='rhymes/videos/')),
                ('external_video_url', models.URLField(blank=True, help_text='Optional embeddable video URL if not uploading a file.')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='rhymes/audio/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='rhymes/thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhymes', to='rhymes.category')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
