# Generated by Django 5.0.6 on 2026-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymes', '0002_rhyme_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rhyme',
            new_name='rhymes_rhym_is_publ_e8a1d1_idx',
            old_name='rhymes_rhyme_pub_categ_idx',
        ),
        migrations.RenameIndex(
            model_name='rhyme',
            new_name='rhymes_rhym_difficu_16c675_idx',
            old_name='rhymes_rhyme_diff_pub_idx',
        ),
        migrations.AlterField(
            model_name='rhyme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rhyme',
            name='external_video_url',
            field=models.URLField(blank=True, help_text='Optional embeddable video URL when a local upload is not used.'),
        ),
        migrations.AlterField(
            model_name='rhyme',
            name='lyrics',
            field=models.TextField(help_text='Lyrics displayed for the learner.'),
        ),
    ]
