# Generated by Django 5.0.6 on 2026-09-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('boy', '👦 Boy'), ('girl', '👧 Girl'), ('cat', '🐱 Cat'), ('dog', '🐶 Dog'), ('lion', '🦁 Lion'), ('monkey', '🐵 Monkey'), ('rabbit', '🐰 Rabbit'), ('panda', '🐼 Panda'), ('unicorn', '🦄 Unicorn'), ('star', '⭐ Star')], default='star', max_length=20),
        ),
    ]
