CATEGORIES = [
    {"slug": "all", "label": "All Rhymes", "icon": "🎵"},
    {"slug": "Animals", "label": "Animals", "icon": "🐾"},
    {"slug": "Nursery", "label": "Nursery", "icon": "🧸"},
    {"slug": "Action", "label": "Action", "icon": "🏃"},
    {"slug": "Nature", "label": "Nature", "icon": "🌿"},
    {"slug": "Festival", "label": "Festival", "icon": "🎁"},
]

RHYMES = [
    {
        "id": 1,
        "title": "Humpty Dumpty",
        "description": "A classic nursery rhyme",
        "category": "Nursery",
        "duration": "02:15",
        "rating": 4.8,
        "thumbnail": "images/reference/humpty.png",
        "audio": "audio/rhymes/humpty-dumpty.mp3",
        "video": "videos/rhymes/humpty-dumpty.mp4",
    },
    {
        "id": 2,
        "title": "Twinkle Twinkle Little Star",
        "description": "Lullaby rhyme",
        "category": "Nature",
        "duration": "01:45",
        "rating": 4.9,
        "thumbnail": "images/reference/twinkle.png",
        "audio": "audio/rhymes/twinkle-twinkle.mp3",
        "video": "videos/rhymes/twinkle-twinkle.mp4",
    },
    {
        "id": 3,
        "title": "Baa Baa Black Sheep",
        "description": "Farmyard rhyme",
        "category": "Animals",
        "duration": "01:30",
        "rating": 4.7,
        "thumbnail": "images/reference/baa-baa.png",
        "audio": "audio/rhymes/baa-baa-black-sheep.mp3",
        "video": "videos/rhymes/baa-baa-black-sheep.mp4",
    },
    {
        "id": 4,
        "title": "Wheels on the Bus",
        "description": "Fun ride rhyme",
        "category": "Action",
        "duration": "02:05",
        "rating": 4.6,
        "thumbnail": "images/rhymes/wheels-on-the-bus.svg",
        "audio": "audio/rhymes/wheels-on-the-bus.mp3",
        "video": "videos/rhymes/wheels-on-the-bus.mp4",
    },
    {
        "id": 5,
        "title": "Mary Had a Little Lamb",
        "description": "Animal rhyme",
        "category": "Animals",
        "duration": "01:50",
        "rating": 4.7,
        "thumbnail": "images/rhymes/mary-had-a-little-lamb.svg",
        "audio": "audio/rhymes/mary-had-a-little-lamb.mp3",
        "video": "videos/rhymes/mary-had-a-little-lamb.mp4",
    },
    {
        "id": 6,
        "title": "Rain Rain Go Away",
        "description": "Rainy day rhyme",
        "category": "Nature",
        "duration": "01:40",
        "rating": 4.5,
        "thumbnail": "images/rhymes/rain-rain-go-away.svg",
        "audio": "audio/rhymes/rain-rain-go-away.mp3",
        "video": "videos/rhymes/rain-rain-go-away.mp4",
    },
    {
        "id": 7,
        "title": "If You're Happy and You Know It",
        "description": "Action rhyme",
        "category": "Action",
        "duration": "01:55",
        "rating": 4.8,
        "thumbnail": "images/rhymes/if-youre-happy.svg",
        "audio": "audio/rhymes/if-youre-happy.mp3",
        "video": "videos/rhymes/if-youre-happy.mp4",
    },
    {
        "id": 8,
        "title": "Jingle Bells",
        "description": "Festival rhyme",
        "duration": "02:10",
        "category": "Festival",
        "rating": 4.9,
        "thumbnail": "images/rhymes/jingle-bells.svg",
        "audio": "audio/rhymes/jingle-bells.mp3",
        "video": "videos/rhymes/jingle-bells.mp4",
    },
]
