# Generated by Django 5.0.6 on 2026-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_constraints_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='quizzes_qui_user_id_a43e13_idx',
            old_name='quizzes_attempt_user_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='quizzes_qui_quiz_id_1c961a_idx',
            old_name='quizzes_attempt_quiz_comp_idx',
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_prompt',
            field=models.FileField(blank=True, help_text='Optional spoken prompt.', null=True, upload_to='quiz/audio_prompts/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Keep it short and simple for early readers.', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
